title: Reflow Add-On
description: A DocumentCloud Add-On that uses K2pdfopt to optimize documents for reading on mobile eReaders and smartphones 
type: object
documents:
  - selected
properties:
  name:
    title: Name
    type: string
