title: Reflow Add-On
description: A DocumentCloud Add-On that uses K2pdfopt to optimize documents for reading on mobile eReaders and smartphones 
type: object
documents:
  - selected
properties:
  height: 
    title: E-reader display pixel height. Default is 745
    type: integer
  width:
    title: E-reader display pixel width. Default is 560
    type: integer
  ppi: 
    title: E-reader display pixels per inch. Default is 167
    type: integer