title: PDF Reflow
description: A DocumentCloud Add-On that uses K2pdfopt to optimize documents for reading on mobile eReaders and smartphones 
instructions: ''
type: object
documents:
  - selected
properties:
  height: 
    title: E-reader display pixel height. Default is 745
    type: integer
    default: 745
  width:
    title: E-reader display pixel width. Default is 560
    type: integer
    default: 560
  dpi: 
    title: E-reader display pixels per inch. Default is 167
    type: integer
    default: 167
  access_level:
    title: Access level for uploaded documents
    type: string
    default: private
    enum:
      - private
      - organization
      - public
  project_id:
    title: Project ID of the project you would like the documents uploaded to (optional)
    type: integer
categories:
  - file
